[llvm]
# They deleted llvm wtf
optimize = true
thin-lto = false
link-shared = false
ninja = false
targets = "X86"
link-jobs = 0
cflags = "-Ob2ity"
cxxflags = "-Ob2ity"
ldflags = "-Wl,-O3 -msse2"
version-suffix = "-eRust-dev"

[build]
cargo-native-static = false
# When compiling from source, you usually want all tools.
#extended = true
build = "x86_64-pc-windows-msvc"
target = [
    "i686-pc-windows-msvc",
    "x86_64-pc-windows-msvc",
]

docs = true
extended = true
tools = [
    "cargo",
    "rustfmt",
]
#verbose = 1

[rust]
channel = "dev"
codegen-backends = ["llvm"]
codegen-units = 1
codegen-units-std = 1
debug = false
dist-src = false
optimize = true
optimize-tests = true
debug-assertions = false

# for creating a downloadable package: python x.py dist.
[dist]
src-tarball = false
missing-tools = true

[install]
prefix = "../dist/rust"
sysconfdir = "."
